name: Build Chrome Extension

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build extension
        run: pnpm run build:prod

      - name: Create extension zip
        run: |
          zip -r chrome-extension.zip dist/*

      - name: Upload extension artifact
        uses: actions/upload-artifact@v5
        with:
          name: chrome-extension
          path: chrome-extension.zip
          retention-days: 30
